### ISSUE TITLE
About beamforming matrix

### ISSUE THREAD

**Issue by jaesusong** [nyuwireless-unipd/mmwave#6]
Hi, I'm trying to do performance evaluation using NYU ns-3 module. 
I guess the beamforming related data files in the directory (mmwave/model/BeamformingMatrix) were generated from matlab m-files. 
Is it possible to get the m-files?
Thank you so much. Your module is very helpful to me.

**Comment by mychele** [comment]
Hi,
I would advise you to use the 3GPP implementation, which is much more recent and relies on C++ code only.
Thanks,
Michele
